name: Gradle Build

on:
  workflow_call:

jobs:
  build:
    name: gradle build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0

      - name: Run build (incl. test)
        run: gradle build -x intTest --no-daemon
